# Generated by Django 5.0.7 on 2024-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=100)),
                ('station_name', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('working_hours_from', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours_to', models.CharField(blank=True, max_length=100, null=True)),
                ('terminal_type', models.CharField(max_length=100)),
                ('avg_rakes_handling', models.FloatField(blank=True, null=True)),
                ('line_count', models.FloatField(blank=True, null=True)),
                ('handling_type', models.CharField(blank=True, max_length=100, null=True)),
                ('warehouse_available_yes_no', models.CharField(blank=True, max_length=10, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('associated_weighbridge', models.CharField(blank=True, max_length=100, null=True)),
                ('alternate_weighbridge', models.CharField(blank=True, max_length=100, null=True)),
                ('tank_handling_yes_no', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terminal_data',
            },
        ),
    ]
